version: '3'
services: 

  app: 
    container_name: review_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/hehe
    depends_on: 
      - mysql
    ports:
      - 4500:80
    links:
      - mysql:mysql

  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    build:
      context: .
      dockerfile: Dockerfile-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=somerandomuser
      - MYSQL_PASSWORD=somerandompassword
    ports:
      - 3306:3306